jhand/__init__.py
from app import create_app

jhand/admin/__init__.py
from .views import admin

jhand/admin/views.py
from datetime import date
import json
import sys
from urlparse import urlparse

from flask import (Blueprint, current_app, flash, g, make_response,
                    jsonify, redirect, render_template,
                    request, url_for)

from flask.ext.classy import FlaskView, route
from flask.ext.security import (current_user, login_required,
                                roles_required)

from ..blog import Comment, Post, PostForm
from ..blog import POST_TYPES
from ..daily import Daily
from .upload import process_upload
from ..utils import s3_upload, s3_signer

admin = Blueprint('admin', __name__, url_prefix='/admin')

class PostAdmin(FlaskView):
    ''' Post Admin View '''

    route_base = '/'
    decorators = [login_required, roles_required('admin')]

    @login_required
    def before_request(self, name, *args , **kwargs):
        g.all_pages = Post.objects(user_ref=current_user.id)
        g.POST_TYPES = POST_TYPES

        for post in g.all_pages:
            post.form = PostForm(prefix=str(post.id),
                                kind=post.kind,
                                slug=post.slug)

        g.daily = Daily.objects(user_ref=current_user.id)
        if (len(g.daily) and
                g.daily[0].is_today() and
                g.daily[0].goal_met()):
            g.wrote_today = True
        else:
            g.wrote_today = False
        g.streak = 1 if g.wrote_today else 0

    def before_index(self, *args, **kwargs):
        for i, day in enumerate(g.daily):
            d1 = day.date.date()
            if day.is_today():
                continue
            elif not day.goal_met():
                break
            elif i > 0:
                d0 = g.daily[i-1].date.date()
            else:
                d0 = date.today()
            delta = d0 - d1
            if delta.days == 1: g.streak += 1

        g.comments = []
        for post in g.all_pages:
            if post.comments:
                for comment in post.comments:
                    comment.post_id = post.id
                    comment.post_title = post.title
                    g.comments.append(comment)


    @route('/', endpoint='index')
    def index(self):
        ''' Main admin post view '''
        form = PostForm()
        return render_template('admin/dashboard.html', newForm=form)

    @route('/posts/', endpoint='post_list')
    def post_list(self):
        ''' Post List '''
        form = PostForm()
        return render_template('admin/post_list.html', newForm=form)

    @route('/<id>', endpoint='post')
    def get(self, id):
        ''' View for a single post '''
        post = Post.objects(id=id).first_or_404()
        post.form = PostForm()
        return render_template('admin/post_edit.html', post=post)

    @route('/upload/', methods=['GET', 'POST'], endpoint='upload')
    def upload(self):
        ''' Upload View '''
        posts = []
        if request.method == 'POST':
            uploaded_files = request.files.getlist('file')
            posts = process_upload(uploaded_files)
            for post in posts:
                post.form = PostForm(prefix=str(post.id),
                                    kind=post.kind, slug=post.slug)
        return render_template('admin/upload.html', posts=posts)

    @route('/export/', endpoint='export')
    @route('/export/<id>', endpoint='export')
    def export(self, id=None):
        '''Export View '''
        if id:
            post_export = Post.objects(
                    id=id).first_or_404().generate_export()
            response = make_response(post_export['content'])
            response.headers['Content-Disposition'] = \
                    'attachment; filename=%s.md' \
                    % post_export['filename']
            return response

        posts = Post.objects()
        urls = []
        for post in posts:
            post_export = post.generate_export()
            url = s3_upload(post_export['filename'],
                    post_export['content'])
            urls.append(url)
        return render_template('admin/export.html', urls=urls)

    def post(self):
        ''' POST Request to create new Post() '''
        form = PostForm(request.form)
        if form.validate_on_submit():
            # TODO: Move this to model
            print 'posting'
            title = form.title.data.strip()
            kind = form.kind.data
            if kind == 'page':
                post = Post(title=title,
                        user_ref=current_user.id, kind=kind)
            elif kind == 'note':
                post = Post(title=title,
                        user_ref=current_user.id, kind=kind)
                link_url = form.category.data
                if link_url:
                    post.link_url = urlparse(link_url).geturl()
            else:
                post = Post(title=title,
                        user_ref=current_user.id, kind='article')
                category = form.category.data.strip().lower()
                if category:
                    post.category = category
            post.save()
            id = post.id
            return redirect(url_for('admin.post', id=id))
        else:
            print form.errors
            flash('Error with form')
            return redirect(request.referrer) or url_for('.post_list')

    def put(self, id):
        try:
            post = Post.objects(id=id).first()
            post = post.validate_json(json.loads(request.data))
            return post.to_dict()
        except:
            _, value, _ = sys.exc_info()
            error = 'Unexpected error: %s' % value
            print error
            # TODO Make these more helpful
            return jsonify({'status':'error', 'error':error}), 400

    def delete(self, id):
        try:
            post = Post.objects(id=id).first_or_404()
            post.delete()
            return jsonify( { 'result': True } )
        except:
            _, value, _ = sys.exc_info()
            error = 'Unexpected error: %s' % value
            print error
            # TODO Make these more helpful
            return jsonify({'status':'error', 'error':error}), 400

    @route('/comments/', endpoint='comments')
    @route('/comments/<id>/', endpoint='comments')
    def comments(self, id=None):
        if id:
            posts = [Post.objects(id=id).first_or_404()]
        else:
            posts = Post.objects(user_ref=current_user.id,
                    kind__in=['note', 'article'])
        return render_template('admin/comments.html', posts=posts)

    @route('/comments/<id>/<comment_id>',
            methods=['GET', 'DELETE'], endpoint='delete_comment')
    def delete_comment(self, id, comment_id):
        Post.objects(id=id).update_one(
                pull__comments__id=Comment(id=comment_id).id)
        return redirect(request.referrer)


@roles_required('admin')
@admin.route('/sign_s3/', endpoint='signS3')
def sign_s3():
    return s3_signer(request)

#Register our View Class
PostAdmin.register(admin)

jhand/app.py
import os
from urlparse import urlparse

from flask import Flask, render_template
from flask.ext.security import MongoEngineUserDatastore

from .admin import admin
from .blog import blog
from .daily import writer
from .user import user, User, Role
from .utils import prettydate

from .config import Config, DevelopmentConfig, ProductionConfig
from .extensions import db, mail, security, assets, md, s3

# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    admin,
    user,
    blog,
    writer,
)

def create_app(config=None, app_name=None, blueprints=None):
    '''Create a Flask app.'''

    if app_name is None:
        app_name = Config.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_relative_config=True)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app

def configure_app(app, config=None):
    '''Different ways of configurations.'''

    # http://flask.pocoo.org/docs/api/#configuration
    if config:
        app.config.from_object(config)
    else:
        try:
            from local import LocalConfig
            app.config.from_object(LocalConfig)
        except:
            app.config.from_object(DevelopmentConfig)

def configure_extensions(app):
    # flask-mongoengine
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # Setup Flask-Security
    user_datastore = MongoEngineUserDatastore(db, User, Role)
    security.init_app(app, user_datastore)

    # Flask assets
    assets.init_app(app)

    # markdown
    md.init_app(app)

    # flask s3
    s3.init_app(app)

    if app.debug:
        from flask.ext.debugtoolbar import DebugToolbarExtension
        toolbar = DebugToolbarExtension(app)

def configure_blueprints(app, blueprints):
    '''Configure blueprints in views.'''

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_template_filters(app):

    @app.template_filter()
    def format_date(value, format='%d %b %Y'):
        return value.strftime(format)

    @app.template_filter()
    def time_ago(value):
        return prettydate(value)

    @app.template_filter()
    def get_domain(url):
        ''' Return just the domain (and subdomain!) for a url
        '''
        parsed_uri = urlparse(url)
        domain = '{uri.netloc}'.format(uri=parsed_uri)
        domain = domain.replace('www.', '')

        return domain

def configure_logging(app):
    '''Configure file(info) and email(error) logging.'''

    if app.debug or app.testing:
        #skip loggin
        return

def configure_hook(app):

    @app.before_request
    def before_request():
        pass

def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500

jhand/blog/__init__.py
from .constants import POST_TYPES
from .forms import PostForm
from .models import Comment, Post
from .views import blog

jhand/blog/views.py
from datetime import datetime

from flask import (abort, Blueprint, flash, g, redirect,
                    render_template, request, url_for)

from flask.ext.classy import FlaskView, route
from flask.ext.security import current_user
from bleach import clean, linkify
from markdown import Markdown

from .constants import ALLOWED_COMMENT_TAGS
from .forms import CommentForm
from .models import Comment, Post

blog = Blueprint('blog', __name__, url_prefix='')

md = Markdown()

class PostView(FlaskView):
    ''' Our base ViewClass for any Post related endpoints
    '''
    route_base = '/'

    def _clean_text(self, text):
        """ Cleans up submitted text from users
        """
        return linkify(clean(md.convert(text),
                tags=ALLOWED_COMMENT_TAGS, strip=True))

    def index(self):
        ''' Our main index view '''
        post = Post.objects(kind__in=['note', 'article'],
                published=True, pub_date__lte=datetime.now()).first()
        home = Post.objects(kind__in=['page'], slug='home',
                published=True, pub_date__lte=datetime.now()).first()
        return render_template('blog/home.html', post=post, home=home)

    @route('/archive/', endpoint='archive',)
    def archive(self):
        ''' Archive View '''
        g.posts = Post.objects(kind__in=['article', 'note'],
                published=True, pub_date__lte=datetime.now())
        return render_template('blog/archive.html')

    @route('/blog/', endpoint='blog')
    @route('/blog/<int:page_num>/', endpoint='blog')
    def blog(self, page_num=1):
        ''' Blog View '''
        g.posts = Post.objects(kind__in=['article', 'note'],
            published=True,
            pub_date__lte=datetime.now()).paginate(
            page=page_num, per_page=3)
        return render_template('blog/blog.html')

    @route('/category/<category>/', endpoint='category')
    @route('/category/<category>/<int:page_num>/', endpoint='category')
    def category(self, category, page_num=1):
        ''' Category Page'''
        if category == 'note':
            g.posts = Post.objects(kind__in=['note'], published=True,
                pub_date__lte=datetime.now()).paginate(page=page_num,
                per_page=10)
            return render_template('blog/category.html',
                    category = category)

        g.posts = Post.objects(kind__in=['article'],
                published=True, category = category,
                pub_date__lte=datetime.now()).paginate(page=page_num,
                per_page=10)
        if len(g.posts.items) == 0:
            flash('Sorry, there are no posts in the <b>%s</b> category.' % category)
            return abort(404)
        return render_template('blog/category.html', category=category)

    @route('/<slug>/', endpoint='page')
    @route('/archive/<slug>/', endpoint='post')
    def get(self, slug):
        ''' View for a single post'''
        form = CommentForm()
        post = Post.objects(slug=slug, published=True).first_or_404()
        if not 'archive' in request.url and post.kind != 'page':
            return redirect(url_for('.post', slug=slug))
        return render_template('blog/post.html', post=post, form=form)

    @route('/archive/<slug>/', methods=['POST'])
    def post(self, slug):
        ''' Post action for comment'''
        form = CommentForm(request.form)
        post = Post.objects(slug=slug, published=True).first_or_404()
        if form.validate_on_submit():
            name = clean(form.name.data.strip(), tags=[], strip=True)
            content = self._clean_text(form.content.data)
            email = form.email.data
            comment = Comment(name=name, content=content, email=email)
            post.update(push__comments=comment)
            flash('Thanks for the comment!')
            return redirect(url_for('.post', slug=slug))
        flash('Errors on comment form')
        return render_template('blog/post.html', post=post, form=form)

#Register our View Classes
PostView.register(blog)

jhand/daily/__init__.py
from .views import writer
from .models import Daily

jhand/daily/views.py
from datetime import datetime, date
import json
import sys

from flask import (Blueprint, current_app, flash, g, jsonify,
                    redirect, render_template, request, url_for)

from flask.ext.classy import FlaskView, route
from flask.ext.security import current_user, roles_required

from .forms import SettingsForm
from .models import Daily, Settings
from ..utils import validate_date

writer = Blueprint('writer', __name__, url_prefix='/admin/writer')

class DailyAdmin(FlaskView):
    ''' Daily Writing View '''

    route_base = '/'
    decorators = [roles_required('admin')]

    def before_request(self, name, *args , **kwargs):
        g.today = date.today()
        g.daily = Daily.objects(user_ref=current_user.id)
        settings = Settings.objects(user_ref=current_user.id).first()
        if not settings:
            settings = Settings(user_ref=current_user.id)
            settings.save()
        g.word_goal = settings.word_goal
        g.daily_words = True

    @route('/', endpoint='index')
    def index(self):
        ''' '''
        return redirect(url_for('.today'))

    @route('/today', endpoint='today')
    @route('/<post_date>', endpoint='daily')
    def get(self, post_date=None):
        ''' Daily Writing View
        '''
        if 'today' in request.path:
            post_date = g.today
        else:
            post_date = datetime.strptime(post_date, '%d-%b-%Y')
        is_today = True if post_date == g.today else False
        post = Daily.objects(
                user_ref=current_user.id, date=post_date).first()
        if post is None:
            if is_today:
                # create a new post for today
                post = Daily(user_ref=current_user.id, date=g.today)
                post.save()
            else:
                flash('No post found for date: %s' %
                        post_date.strftime('%d-%b-%Y'))
                return redirect(url_for('.today'))
        return render_template('admin/writer.html',
                post=post, is_today=is_today)

    def put(self, id):
        try:
            post = Daily.objects(id=id).first()
            post = post.validate_json(json.loads(request.data))
            return post.to_dict()
        except:
            print 'Unexpected error:', sys.exc_info()[0]
            # TODO Make these more helpful
            return jsonify(status='error', error=''), 400

    @route('/settings', methods=['GET', 'POST'])
    def settings(self):
        ''' '''
        form = SettingsForm(request.form)
        settings = Settings.objects(user_ref=current_user.id).first()
        if form.validate_on_submit():
            if not settings:
                settings = Settings(user_ref=current_user.id)
            settings.word_goal = form.data['word_goal']
            settings.save()
        elif settings:
            form.word_goal.data = settings.word_goal
        return render_template('admin/writer_settings.html', form=form)


#Register our View Class
DailyAdmin.register(writer)

jhand/user/__init__.py
from .models import User, Role
from .views import user

jhand/user/views.py
from flask import (Blueprint, abort)

from flask.ext.security import login_required

from .models import User


user = Blueprint('user', __name__, url_prefix='/user')


@login_required
@user.route('/')
def index():
    return abort(404)

jhand/templates/blog/_blog_base.html
{% extends "_base.html" %}
{% import "macros/_css.html" as css %}
    {%- block css -%}
        {{ css.render_css('main') }}
    {%- endblock -%}

    {%- block siteheader %}
        {%- if current_user.has_role('admin') -%}
            <div class="admin-nav">
                <a class="admin-link small-caps useicons" href="{{url_for('admin.index')}}" data-no-instant>&#xe600;</a>
            </div>
        {%- endif %}
            <div class="site-head wrapper cf">
                <header role="banner" class="banner medium-float-left">
                    <h1 class="name small-caps"><a class="" href="{{url_for('blog.PostView:index')}}">Joe Hand</a></h1>
                </header>
                {%- include "blog/partials/_site-nav.html" %}
            </div>
            <div class="site-head-border strip"></div>
    {%- endblock siteheader -%}

    {% block sitefooter %}
            <footer role="contentinfo" class="footer">
                <div class="bottom cf">
                    {% include "partials/_social.html" %}
                    <div class="wrapper">
                        <span class="copyright medium-float-left">
                            <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Copyright © 2014</a>
                            &nbsp;·&nbsp; Joe Hand
                        </span>
                        <span class="made medium-float-right">
                            <a href="{{url_for('blog.archive')}}">Archive</a>
                            &nbsp;·&nbsp;<a href="{{url_for('blog.page', slug='about')}}">Made by <span class="useicons">&#xe635;</span></a>
                        </span>
                    </div>
                </div>
            </footer>
    {%- endblock sitefooter %}

{%- block footer_js %}
{%- set js_name = 'instantclick' -%}
{%- assets filters="jsmin", output="build/" + js_name + ".%(version)s.min.js",
  "js/libs/" + js_name + ".js" -%}
    <script src="{{ ASSET_URL }}"></script>
{%- endassets -%}
        {% if not config.DEBUG and not current_user.has_role('admin') %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-37465100-3', 'joeahand.com');

            InstantClick.on('change', function() {
                ga('send', 'pageview', location.pathname + location.search);
            });

            InstantClick.init();
        </script>
        {%- else -%}
        <script>
            InstantClick.init();
        </script>
        {%- endif -%}
{%- endblock footer_js %}

jhand/templates/blog/archive.html
{% extends "blog/_blog_base.html" %}

{%- block content %}
    <div class="post-archive">
    {%- for post in g.posts %}
        {% if loop.first -%}
            {%- set year = post.pub_date.year -%}
            <div class="year crossbars">{{year}}</div>
        {%- elif post.pub_date.year < year -%}
            {%- set year = post.pub_date.year -%}
            <div class="year crossbars">{{year}}</div>
        {% endif -%}

        <div class="post-list" data-id="{{post.id}}">
            <div class="cf">
                <h4 class="title float-left">
                    <a href="{{url_for('blog.post', slug=post.slug)}}">{{post.title}}</a>
                </h4>
                <a href="{{url_for('.category', category=post.category)}}" class="category float-right">
                    {%- if post.category -%}{{post.category}}{%- endif -%}
                </a>
            </div>
            <div class="cf">
                <span class="pub_date float-left">{{post.pub_date.strftime('%B %d')}}</span>
            </div>
        </div>
    {% endfor -%}
    </div>
{% endblock -%}

jhand/templates/blog/blog.html
{% extends "blog/_blog_base.html" %}
{% import "macros/_pagination.html" as page %}

{%- block content %}
        {%- for post in g.posts.items %}
        <section class="post-full" data-id="{{post.id}}">
                <header>
                    {%- if post.kind == 'article' -%}
                    <h2 class="title"><a href="{{url_for('blog.post', slug=post.slug)}}">{{post.title}}</a></h2>
                    {%- elif post.kind == 'note' -%}
                    <h3 class="title"><a href="{{url_for('blog.post', slug=post.slug)}}">{{post.title}}</a></h3>
                        {%- if post.link_url -%}
                        <h5 class="link_url">
                            <a href="{{post.link_url}}"><span class="useicons">&#xe61e;</span><span class="link_url">{{post.link_url|get_domain}}</span></a>
                        </h5>
                        {%- endif -%}
                    {%- endif -%}
                    <h5 class="category small-caps"><a href="{{url_for('.category', category='note')}}">{{post.category}}</a></h5>
                </header>
                {%- if post.kind == 'article' -%}
                <article class="content">
                    {% if post.content %}{{post.content|truncate(250)|markdown|safe}}{% endif %}
                </article>
                <footer class="post-footer">
                  <a class="small-caps"href="{{url_for('blog.post', slug=post.slug)}}"><span class="useicons">&#xe630;</span><span class="pub_date">{{post.pub_date.strftime('%B %Y')}}</span></a>
                </footer>
                {%- elif post.kind == 'note' -%}
                <article class="content">
                    {% if post.content %}{{post.content|markdown|safe}}{% endif %}
                </article>
                <footer class="post-footer">
                  <a class="small-caps" rel="bookmark" title="Permalink" href="{{url_for('blog.post', slug=post.slug)}}"><span class="useicons">&#xe630;</span><span class="pub_date">{{post.pub_date.strftime('%B %Y')}}</span></a>
                </footer>
                {%- endif -%}
            </section>
        {% endfor -%}

        {{ page.render_pagination(g.posts, '.blog') }}
{%- endblock -%}

jhand/templates/blog/category.html
{% extends "blog/_blog_base.html" %}
{% import "macros/_pagination.html" as page %}

{%- block content %}
                {%- if category == 'note' -%}
        <h2 class="category-header small-caps">Notes</h2>
                {%- else -%}
        <h2 class="category-header small-caps">{{category}}</h2>
                    {%- endif -%}
        {%- for post in g.posts.items %}
        <section class="post-full" data-id="{{post.id}}">
                <header>
                    <h2 class="title"><a href="{{url_for('blog.post', slug=post.slug)}}">{{post.title}}</a></h2>
                    {%- if post.kind == 'note' and post.link_url -%}
                    <h5 class="link_url">
                        <a href="{{post.link_url}}"><span class="useicons">&#xe61e;</span><span class="link_url">{{post.link_url|get_domain}}</span></a>
                    </h5>
                    {%- endif -%}
                </header>
                {%- if post.kind == 'article' -%}
                <article class="content">
                    {% if post.content %}{{post.content|truncate(250)|markdown|safe}}{% endif %}
                </article>
                <footer class="post-footer">
                  <a class="small-caps"href="{{url_for('blog.post', slug=post.slug)}}"><span class="useicons">&#xe630;</span><span class="pub_date">{{post.pub_date.strftime('%B %Y')}}</span></a>
                </footer>
                {%- elif post.kind == 'note' -%}
                <article class="content">
                    {% if post.content %}{{post.content|markdown|safe}}{% endif %}
                </article>
                <footer class="post-footer">
                  <a class="small-caps" rel="bookmark" title="Permalink" href="{{url_for('blog.post', slug=post.slug)}}"><span class="useicons">&#xe630;</span><span class="pub_date">{{post.pub_date.strftime('%B %Y')}}</span></a>
                </footer>
                {%- endif -%}
            </section>
        {% endfor -%}

        {{ page.render_pagination(g.posts, '.category', category) }}
{%- endblock -%}

jhand/templates/blog/home.html
{% extends "blog/_blog_base.html" %}

{%- block body_class %}home{%- endblock body_class -%}
    {%- block siteheader %}
        {%- if current_user.has_role('admin') -%}
            <div class="admin-nav">
                <a class="admin-link small-caps useicons" href="{{url_for('admin.index')}}" data-no-instant>&#xe600;</a>
            </div>
        {%- endif %}
            <div class="site-head wrapper cf">
                {%- include "blog/partials/_site-nav.html" %}
            </div>
    {%- endblock siteheader -%}

    {%- block content %}
                    <div class="home-head wrapper">
                        <header role="banner" class="">
                            <h1 class="name small-caps"><a class="" href="{{url_for('blog.PostView:index')}}">Joe Hand</a>
                                </h1>
                        </header>
                    </div>
        {%- if home %}
            {{home.content|markdown|safe}}
            <hr/>
            {%- include "blog/partials/_post_trunc.html" %}
        {% elif post %}
            {%- include "blog/partials/_post_full.html" %}
        {%- endif -%}
    {%- endblock -%}

jhand/templates/blog/index.html
{% extends "blog/_blog_base.html" %}

{%- block content -%}
        {% if post %}
        {%- include "blog/partials/_post_full.html" %}
        {% endif %}
{%- endblock -%}

jhand/templates/blog/post.html
{% extends "blog/_blog_base.html" %}
{% import "macros/_wtf.html" as wtf -%}


{%- block content %}
        {% include "blog/partials/_post_full.html" %}

        {# Need spam control =(
        {%- if post.kind != 'page' %}
        <form class="form comment-form" method="post" action="{{request.url}}">
            <fieldset>
            {{ form.hidden_tag() }}
            {{ wtf.regular_field(form.content, rows=8) }}
            {{ wtf.regular_field(form.name) }}
            {{ wtf.regular_field(form.email, description="Will not be published") }}
            <button type="submit" class="float-right button button-small">Submit</button>
            </fieldset>
        </form>
        {%- if post.comments|length > 0 %}
        <div class="comment-list">
            <h5 class="h3">{% if post.comments|length == 1 %}{{ post.comments|length }} Comment {% else %}{{ post.comments|length }} Comments{% endif %}</h5>
        {%- for comment in post.comments %}
            <div class="comment">
                <img src="{{comment.avatar(48)}}" class="image">
                <div class="cf">
                <span class="h6 float-left name">{{comment.name}}</span>
                <span class="float-right date">{{comment.created_at|time_ago}}</span>
                </div>
                <div class="comment-content">{{comment.content|safe|urlize(40, true)}}</div>
            </div>
        {%- endfor %}
        </div>
        {%- endif %}
        {%- endif %}
        #}
{% endblock %}